-- Desktop-only PCSX-Redux adapter. This file is never compiled into the PSX game.
local port, token = EPOK_PORT, EPOK_TOKEN
local client = luv.new_tcp()
-- Debug/status headers are small and precede the pixels. Do not let Nagle's
-- algorithm delay them behind the previous frame's ACK on this local socket.
client:nodelay(true)
local pending = ''
local sequence = 0
local vsyncs = 0
local ffi = require('ffi')
local debug_available, debug_paused, debug_at_node = false, false, false
local debug_latest, debug_hook, debug_return, debug_return_pc
local debug_points, debug_traces, debug_dropped = {}, {}, 0
local debug_stop_next = false
local function ram_offset(address, length)
    if type(address) ~= 'number' or address ~= math.floor(address) then return nil end
    local offset
    if address >= 0 and address < 0x200000 then offset = address
    elseif address >= 0x80000000 and address < 0x80200000 then offset = address - 0x80000000
    elseif address >= 0xa0000000 and address < 0xa0200000 then offset = address - 0xa0000000 end
    if not offset or offset % 4 ~= 0 or offset + length > 0x200000 then return nil end
    return offset
end
-- This file is generated by the editor after linking, not loaded from a game
-- asset. Numeric addresses are range checked before touching emulator memory.
local config_ok, debug_config = pcall(dofile, EPOK_DEBUG_CONFIG or '')
if config_ok and type(debug_config) == 'table' and debug_config.version == 1 then
    local snapshot_offset = ram_offset(debug_config.snapshot, 476)
    if ram_offset(debug_config.hook, 4) and snapshot_offset then
        if type(debug_config.breakpoints) == 'table' and #debug_config.breakpoints <= 32 then
            for _, point in ipairs(debug_config.breakpoints) do
                if type(point.class) == 'number' and point.class >= 0 and point.class <= 4294967295 and
                   type(point.node) == 'number' and point.node >= 0 and point.node <= 4294967295 and point.owner == 65535 then
                    debug_points[#debug_points + 1] = {class=point.class,node=point.node,owner=65535,generation=0}
                end
            end
        end
        local memory = PCSX.getMemPtr()
        local function checkpoint()
            local words = ffi.cast('const uint32_t*', memory + snapshot_offset)
            if tonumber(words[0]) ~= 0x55425144 or tonumber(words[1]) ~= 1 or tonumber(words[6]) > 16 then
                error('Invalid Blueprint snapshot ABI')
            end
            debug_latest = ffi.string(memory + snapshot_offset, 476)
            if #debug_traces < 128 then
                debug_traces[#debug_traces + 1] = ffi.string(memory + snapshot_offset + 8, 16)
            else debug_dropped = math.min(debug_dropped + 1, 4294967295) end
            local class, node = tonumber(words[2]), tonumber(words[3])
            local owner, generation = tonumber(words[4]), tonumber(words[5])
            local stop = debug_stop_next
            for _, point in ipairs(debug_points) do
                if point.class == class and point.node == node and
                    (point.owner == 65535 or (point.owner == owner and point.generation == generation)) then stop = true end
            end
            if stop then
                debug_stop_next = false
                debug_paused, debug_at_node = true, true
                debug_return_pc = tonumber(PCSX.getRegisters().GPR.n.ra)
                PCSX.pauseEmulator()
            end
        end
        local ok, hook = pcall(PCSX.addBreakpoint, debug_config.hook, 'Exec', 4, 'Epok Blueprint node', function()
            local success, why = pcall(checkpoint)
            if not success then
                debug_available = false
                printError('Epok Blueprint debugger: ' .. tostring(why))
                return false
            end
        end)
        if ok then debug_hook, debug_available = hook, true end
    end
end
local function debug_resume(step)
    if not debug_available then return false end
    debug_stop_next = step
    if debug_at_node then
        if not ram_offset(debug_return_pc, 4) then return false end
        -- Do not guess whether Redux suppresses the breakpoint at its current
        -- PC after resuming. Disable the hook until this invocation returns;
        -- re-arm at its return address and stop on the following graph node.
        debug_hook:disable()
        if debug_return then debug_return:remove(); debug_return = nil end
        debug_return = PCSX.addBreakpoint(debug_return_pc, 'Exec', 4, 'Epok Blueprint continue', function()
            debug_hook:enable()
            debug_return = nil
            return false
        end)
    end
    debug_paused, debug_at_node = false, false
    PCSX.resumeEmulator()
    return true
end
local function debug_command(line)
    if not debug_available then return false end
    if line == 'C' then debug_points = {}; return true end
    if line == 'P' then
        if not debug_at_node then debug_stop_next = true; PCSX.resumeEmulator() end
        return true
    end
    if line == 'N' then return debug_resume(true) end
    if line == 'R' then return debug_resume(false) end
    local command, class, node, owner, generation = line:match('^([BX]) (%d+) (%d+) (%d+) (%d+)$')
    class, node, owner, generation = tonumber(class), tonumber(node), tonumber(owner), tonumber(generation)
    if not command or not class or class > 4294967295 or not node or node > 4294967295 or not owner or owner > 65535 or not generation or generation > 4294967295 then return false end
    for i, point in ipairs(debug_points) do
        if point.class == class and point.node == node and point.owner == owner and point.generation == generation then
            if command == 'X' then table.remove(debug_points, i) end
            return true
        end
    end
    if command == 'X' then return true end
    if #debug_points == 32 then return false end
    debug_points[#debug_points + 1] = {class=class,node=node,owner=owner,generation=generation}
    return true
end
local function debug_frame()
    local count = math.min(#debug_traces, 64)
    local packet = {string.format('EPKD1 %d %d %d %d %d %d\n', debug_available and 1 or 0,
        debug_paused and 1 or 0, debug_at_node and 1 or 0, debug_dropped, count, debug_latest and 476 or 0)}
    if debug_latest then packet[#packet + 1] = debug_latest end
    for _ = 1, count do packet[#packet + 1] = table.remove(debug_traces, 1) end
    debug_dropped = 0
    client:write(packet)
end
EPOK_VSYNC_LISTENER = PCSX.Events.createEventListener('GPU::Vsync', function() vsyncs = vsyncs + 1 end)
local pad = PCSX.SIO0.slots[1].pads[1]
-- An explicit project Play option. Existing pad bindings and other projects stay unchanged.
if EPOK_ANALOG_CONTROLLER then
    PCSX.settings.pads[1].DeviceType = 'Analog'
    PCSX.settings.pads[1].Connected = true
    pad.map()
    pad.setAnalogMode(true)
end
local buttons = {'SELECT','L3','R3','START','UP','RIGHT','DOWN','LEFT',
                 'L2','R2','L1','R1','TRIANGLE','CIRCLE','CROSS','SQUARE'}
local function release()
    for _, name in ipairs(buttons) do
        local button = PCSX.CONSTS.PAD.BUTTON[name]
        if button then pad.clearOverride(button) end
    end
end
local function close()
    release()
    if debug_hook then debug_hook:remove(); debug_hook = nil end
    if debug_return then debug_return:remove(); debug_return = nil end
    if not client:is_closing() then client:close() end
end
local function frame(mask)
    debug_frame()
    for i, name in ipairs(buttons) do
        local button = PCSX.CONSTS.PAD.BUTTON[name]
        if button then
            if bit.band(mask, bit.lshift(1, i - 1)) ~= 0 then pad.setOverride(button)
            else pad.clearOverride(button) end
        end
    end
    local ss = PCSX.GPU.takeScreenShot()
    if ss.width == 0 or ss.height == 0 then client:write('EPKF0\n'); return end
    local depth = tonumber(ss.bpp) == 0 and 2 or 3
    sequence = sequence + 1
    local actual = 0
    for i, name in ipairs(buttons) do
        local button = PCSX.CONSTS.PAD.BUTTON[name]
        if button and pad.getButton(button) then actual = bit.bor(actual, bit.lshift(1, i-1)) end
    end
    local header = string.format('EPKF1 %d %d %d %d %d %.0f %d\n', ss.width, ss.height, depth, sequence, actual, tonumber(PCSX.getCPUCycles()), vsyncs)
    client:write({header, tostring(ss.data)})
end
client:connect('127.0.0.1', port, function(err)
    if err then close(); return end
    client:write('EPOK ' .. token .. '\n')
    client:read_start(function(readerr, chunk)
        if readerr or not chunk then close(); return end
        pending = pending .. chunk
        if #pending > 128 then close(); return end
        local line, rest = pending:match('^([^\n]*)\n(.*)$')
        if line then
            pending = rest
            local command, value = line:match('^([FS]) (%d+)$')
            if not command then
                PCSX.nextTick(function()
                    local ok, accepted = pcall(debug_command, line)
                    client:write(ok and accepted and 'EPKA1 1\n' or 'EPKA1 0\n')
                end)
                return
            end
            local mask = tonumber(value)
            if not mask or mask > 65535 then close(); return end
            PCSX.nextTick(function()
                if command == 'S' then
                    EPOK_STEP_LISTENER = PCSX.Events.createEventListener('GPU::Vsync', function()
                        PCSX.pauseEmulator()
                        EPOK_STEP_LISTENER:remove()
                        EPOK_STEP_LISTENER = nil
                    end)
                    PCSX.resumeEmulator()
                end
                local ok, why = pcall(frame, mask)
                if not ok then printError('Epok bridge: ' .. tostring(why)); close() end
            end)
        end
    end)
end)
EPOK_QUIT_LISTENER = PCSX.Events.createEventListener('Quitting', close)
