#pragma once
#include <stdint.h>

#define EPOK_NATIVE_PLAY_MAGIC 0x314e5045u /* "EPN1" */
#define EPOK_NATIVE_PLAY_ACTOR_WORDS 16u
#define EPOK_NATIVE_PLAY_AUDIO_WORDS 6u
#define EPOK_NATIVE_PLAY_AUDIO_LIMIT 256u
