"""Compose terrain tiles into one atlas the PSX texture importer accepts.

A terrain samples one tile per cell out of a single texture, because the
console has no multitexturing and a whole-terrain baked texture would give a
handful of texels per cell. So the ground is a grid of tiles in one image of
at most 256x256, and the cell picks which tile it shows.

Tile order is row-major, matching `terrain_compile::tile_uv`: tile 0 is the
top-left, then left to right, then down. Set the terrain's Atlas columns/rows
to the same grid.

`--autotile` instead composes the 4x4 layout the terrain baker resolves
automatically: row 0 is the base material in four variants, and rows 1-3 are
overlays, each as fill, edge, corner and inner corner over the base. The
transition tiles are generated by masking the overlay onto the base, because a
console with no multitexturing can only change materials at a cell boundary --
the blend has to be painted into the tile itself.

Orientation follows the renderer: at rotation 0 a tile is seen with its top
edge toward -Z, so every transition is drawn with the base material at the
top, and at the top-right for the corner shapes.
"""
import argparse
import math
import pathlib
import sys

from PIL import Image, ImageFilter

MAX_ATLAS = 256


# Generated at this size, then downscaled with everything else. Masking at the
# tile's final 64 px would turn a soft boundary into a staircase.
MASK_SIZE = 256


def wobble(t, seed, amplitude):
    """Deterministic irregular offset in -amplitude..amplitude."""
    total = 0.0
    for harmonic, weight in ((1.0, 0.6), (2.3, 0.3), (5.1, 0.1)):
        total += weight * math.sin(t * math.tau * harmonic + seed * (harmonic + 1.7))
    return total * amplitude


def transition_mask(shape, seed):
    """Coverage of the BASE material over an overlay tile, 255 = all base.

    `shape` is "edge" (base along the top), "corner" (base along the top and
    the right) or "inner" (base biting the top-right corner only).
    """
    size = MASK_SIZE
    mask = Image.new("L", (size, size), 0)
    pixels = mask.load()
    for y in range(size):
        for x in range(size):
            u, v = x / size, y / size
            if shape == "edge":
                base = v < 0.42 + wobble(u, seed, 0.10)
            elif shape == "corner":
                base = v < 0.40 + wobble(u, seed, 0.09) or u > 0.60 + wobble(v, seed + 3, 0.09)
            else:
                # Distance from the top-right corner, wobbled around the arc.
                dx, dy = 1.0 - u, v
                angle = math.atan2(dy, max(dx, 1e-6)) / math.tau
                base = math.hypot(dx, dy) < 0.40 + wobble(angle, seed + 7, 0.07)
            pixels[x, y] = 255 if base else 0
    # Feather so the boundary survives the downscale as a soft line rather
    # than a staircase of its own.
    return mask.filter(ImageFilter.GaussianBlur(size / 64))


def load(path, size):
    with Image.open(path) as image:
        return image.convert("RGB").resize((size, size), Image.LANCZOS)


def autotile_layout(base, overlays):
    """Row 0: base variants. Rows 1-3: fill, edge, corner, inner per overlay."""
    if not 1 <= len(base) <= 4:
        raise SystemExit("--base takes one to four images")
    if not 1 <= len(overlays) <= 3:
        raise SystemExit("--overlay takes one to three images")
    row0 = [load(p, MASK_SIZE) for p in base]
    while len(row0) < 4:
        row0.append(row0[len(row0) % len(base)])
    tiles = list(row0)
    blend = row0[0]
    for index, path in enumerate(overlays):
        fill = load(path, MASK_SIZE)
        tiles.append(fill)
        for shape in ("edge", "corner", "inner"):
            tiles.append(Image.composite(blend, fill, transition_mask(shape, index * 11 + 1)))
    while len(tiles) < 16:
        tiles.append(row0[0])
    return tiles


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("sources", nargs="*", type=pathlib.Path, help="Tile images, in tile order")
    parser.add_argument("--autotile", action="store_true", help="Compose the 4x4 autotile layout")
    parser.add_argument("--base", nargs="+", type=pathlib.Path, default=[])
    parser.add_argument("--overlay", action="append", type=pathlib.Path, default=[])
    parser.add_argument("--output", required=True, type=pathlib.Path)
    parser.add_argument("--cols", type=int, default=0, help="Default: square-ish grid")
    parser.add_argument("--rows", type=int, default=0)
    parser.add_argument(
        "--tile",
        type=int,
        default=0,
        help="Pixels per tile. Default: the largest that keeps the atlas within 256.",
    )
    args = parser.parse_args()

    generated = None
    if args.autotile:
        if args.sources:
            raise SystemExit("--autotile takes --base and --overlay, not positional sources")
        generated = autotile_layout(args.base, args.overlay)
        args.cols = args.rows = 4
    sources = args.sources or [None] * len(generated or [])

    count = len(sources)
    cols = args.cols or min(count, 2 if count <= 4 else 3 if count <= 9 else 4)
    rows = args.rows or -(-count // cols)
    if cols * rows < count:
        raise SystemExit(f"{count} tiles do not fit a {cols}x{rows} grid")

    tile = args.tile or MAX_ATLAS // max(cols, rows)
    if tile < 8:
        raise SystemExit(f"{cols}x{rows} leaves {tile} px per tile; use fewer tiles")
    if cols * tile > MAX_ATLAS or rows * tile > MAX_ATLAS:
        raise SystemExit(
            f"{cols}x{rows} tiles of {tile} px is {cols * tile}x{rows * tile}; "
            f"the importer accepts at most {MAX_ATLAS} per axis"
        )

    atlas = Image.new("RGB", (cols * tile, rows * tile))
    labels = ["fill", "edge", "corner", "inner"]
    for index, source in enumerate(sources):
        if generated is not None:
            # LANCZOS keeps a hand-painted tile readable at 64-128 px; the
            # engine quantizes to a 256-colour CLUT afterwards.
            patch = generated[index].resize((tile, tile), Image.LANCZOS)
            row, col = divmod(index, cols)
            name = f"base variant {col}" if row == 0 else f"overlay {row} {labels[col]}"
        else:
            patch = load(source, tile)
            name = source.name
        atlas.paste(patch, ((index % cols) * tile, (index // cols) * tile))
        print(f"  tile {index}: {name} -> {tile}x{tile}")

    args.output.parent.mkdir(parents=True, exist_ok=True)
    atlas.save(args.output, optimize=True)
    colors = len(atlas.getcolors(maxcolors=1 << 24) or [])
    print(
        f"Wrote {args.output} ({atlas.width}x{atlas.height}, {cols}x{rows} tiles, "
        f"{args.output.stat().st_size} bytes, {colors} distinct colours)"
    )
    if colors > 255:
        print(
            "Note: the importer quantizes to a 256-entry CLUT with index 0 reserved,"
            " so expect some colour loss.",
            file=sys.stderr,
        )


if __name__ == "__main__":
    main()
