#!/usr/bin/env bash
# Create Desktop shortcuts for the development editor on macOS: one that
# compiles the current checkout, one that launches what was compiled last.
set -euo pipefail

[[ "$(uname -s)" == "Darwin" ]] || { echo "Desktop shortcuts are available on macOS only." >&2; exit 1; }

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
desktop="$HOME/Desktop"
[[ -d "$desktop" ]] || { echo "No Desktop directory at $desktop" >&2; exit 1; }

builder="$desktop/Compilar Epok.command"
launcher="$desktop/Epok Engine (debug).app"

# Finder and Terminal launches do not inherit an interactive shell's PATH, so
# both shortcuts add the locations cargo and the MIPS toolchain install into.
path_line='export PATH="/opt/homebrew/bin:$HOME/.cargo/bin:$PATH"'

cat > "$builder" <<EOF
#!/bin/bash
# Generated by tools/desktop-shortcuts-macos.sh
$path_line
cd "$root" || { echo "Repository not found at $root"; read -r -p "Press Return to close."; exit 1; }
printf '\033]0;Compilar Epok\007'
echo "Repository: $root"
echo "Branch:     \$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo unknown)"
echo
if make build; then
    echo
    echo "Done. Launch 'Epok Engine (debug)' on the Desktop."
else
    status=\$?
    echo
    echo "Build failed (exit \$status). The errors are above."
    read -r -p "Press Return to close."
    exit \$status
fi
EOF
chmod 755 "$builder"

rm -rf "$launcher"
mkdir -p "$launcher/Contents/MacOS" "$launcher/Contents/Resources"

cat > "$launcher/Contents/MacOS/epok-launcher" <<EOF
#!/bin/bash
# Generated by tools/desktop-shortcuts-macos.sh
$path_line
binary="$root/target/debug/epok-editor"
if [[ ! -x "\$binary" ]]; then
    osascript -e 'display alert "Epok is not compiled yet" message "Run \"Compilar Epok\" on the Desktop first." as critical' >/dev/null
    exit 1
fi
cd "$root"
exec "\$binary"
EOF
chmod 755 "$launcher/Contents/MacOS/epok-launcher"

sips -s format icns "$root/resources/branding/epok.png" \
    --out "$launcher/Contents/Resources/EpokEngine.icns" >/dev/null

cat > "$launcher/Contents/Info.plist" <<'EOF'
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0"><dict>
  <key>CFBundleDevelopmentRegion</key><string>en</string>
  <key>CFBundleDisplayName</key><string>Epok Engine (debug)</string>
  <key>CFBundleExecutable</key><string>epok-launcher</string>
  <key>CFBundleIconFile</key><string>EpokEngine</string>
  <key>CFBundleIdentifier</key><string>com.epok.engine.debug</string>
  <key>CFBundleInfoDictionaryVersion</key><string>6.0</string>
  <key>CFBundleName</key><string>Epok Engine (debug)</string>
  <key>CFBundlePackageType</key><string>APPL</string>
  <key>CFBundleShortVersionString</key><string>0.0</string>
  <key>CFBundleVersion</key><string>1</string>
  <key>LSMinimumSystemVersion</key><string>11.0</string>
</dict></plist>
EOF

codesign --force --deep --sign - "$launcher" >/dev/null

echo "Created: $builder"
echo "Created: $launcher"
echo "Both point at $root and follow whatever branch is checked out there."
